#!/usr/bin/env bash
# Redirecting to another page

# Update package list and install Nginx
apt-get update
apt-get install -y nginx

# Create directory and index.html file
mkdir /etc/nginx/html
echo "Holberton School" > /etc/nginx/html/index.html

# Set up Nginx server block with the correct redirection
cat << EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /etc/nginx/html;
    index index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF

# Restart Nginx to apply the changes
service nginx restart

# Test the redirection using curl
curl -sI http://localhost/redirect_me
