#!/usr/bin/env bash
# Redirecting to another page

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
echo "Holberton School" > /etc/nginx/html/index.html

# Update the Nginx server block with the correct redirection
cat << EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /etc/nginx/html;
    index index.html index.htm;

    location /redirect_me {
        return 301 http://youtube.com/;
    }
}
EOF

service nginx restart

# Test the redirection using curl
curl -sI http://localhost/redirect_me
